name: pypff-CI

on:
  push:
    branches: ["dev", "opt", "master"]

jobs:
  pypff-test:
    name: pypff-test
    runs-on: ubuntu-latest

    steps:
      - name: clone pypff
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync --all-extras

      - name: run test
        run: uv run pypff test all
